--User authentication table
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY, --SERIAL auto increments
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    passwordHash VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
    id BIGSERIAL PRIMARY KEY,
    ownerID BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    dueAt TIMESTAMP NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fkTaskOwner
    FOREIGN KEY(ownerID) REFERENCES users(id)
    ON DELETE CASCADE
);
